version: '3.8'

services:
  # database:
  #   image: mysql:8.0.25
  #   container_name: liferay-portal-7.4_db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=lportal
  #   command: --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --lower-case-table-names=0
  #   volumes:
  #     - ./mysql-dump:/docker-entrypoint-initdb.d
  #   ports:
  #     - "3306:3306"

  database:
    image: gvenzl/oracle-xe # Imagem Oracle XE para desenvolvimento
    container_name: liferay-portal-7.4_db
    ports:
      - "1521:1521"
      - "5500:5500" # Porta de administração web, se necessário
    environment:
      - ORACLE_PASSWORD=root
      - ORACLE_DISABLE_ASYNCH_IO=true
    volumes:
      #- oracle_data:/opt/oracle/oradata
      - ./ora-dump:/opt/oracle/dump 
      - ./ora-scripts:/docker-entrypoint-initdb.d/
    restart: always

  liferay:
    image: liferay/dxp:7.3.10-u33
    environment:
      - LIFERAY_JVM_OPTS=-Xms6g -Xmx6g -Djdk.util.zip.disableZip64ExtraFieldValidation=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=oracle.jdbc.OracleDriver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=database)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)))
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=lportal
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=root
      - LIFERAY_PASSWORDS_PERIOD_DEFAULT_PERIOD_POLICY_PERIOD_CHANGE_PERIOD_REQUIRED=false
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=10
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS_PERIOD_VERIFY=false
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS=true
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_SEND_PERIOD_PASSWORD_PERIOD_RESET_PERIOD_LINK=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED=false
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=false
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE=false
      - LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE=domain
      - LIFERAY_BUFFERED_PERIOD_INCREMENT_PERIOD_ENABLED=true
      - LIFERAY_XML_PERIOD_SITEMAP_PERIOD_INDEX_PERIOD_ENABLED=false
      - LIFERAY_HTTP_PERIOD_HEADER_PERIOD_VERSION_PERIOD_VERBOSITY=off
      - LIFERAY_LOCALE_PERIOD_PREPEND_PERIOD_FRIENDLY_PERIOD_URL_PERIOD_STYLE=0
      - LIFERAY_BROWSER_PERIOD_LAUNCHER_PERIOD_URL=
      - GLOWROOT_ENABLED=
      - LIFERAY_DISABLE_TRIAL_LICENSE=TRUE
    ports:
      - "8080:8080"
      - "11311:11311"
      - "8000:8000"
    volumes:
      - ./liferay-deploy:/mnt/liferay/deploy
      - ./liferay-files:/mnt/liferay/files
      - ./liferay-logs:/opt/liferay/logs
      - ./liferay-document-library:/opt/liferay/data/document_library
      - ./liferay-patching:/mnt/liferay/patching
    depends_on:
      - database
      - search

  search:
    image: marceltanuri/elasticsearch-with-plugins:7.17.10
    container_name: liferay-portal-7.4_search
    environment:
      - "cluster.name=LiferayElasticsearchCluster"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "node.name=es-node1"
      - "xpack.security.enabled=false"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
