services:
  database:
    image: mysql:8.0.25
    container_name: liferay-portal-7.4_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --lower-case-table-names=0
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  liferay:
    build:
      context: ./liferay
      dockerfile: Dockerfile
    container_name: liferay-local
    env_file:
      - ./liferay/.env
    ports:
      - "8080:8080"
    volumes:
      - ./liferay/deploy:/mnt/liferay/deploy
      - ./liferay/config/.all:/mnt/liferay/files
      - ./liferay/logs:/opt/liferay/logs
      - ./liferay/document-library:/opt/liferay/data/document_library
      - ./liferay/patching:/mnt/liferay/patching
    depends_on:
      - database
      - search
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webserver:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - liferay
  
  search:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: liferay-portal-7.4_search
    env_file:
      - ./elasticsearch/.env
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  
  fake-oauth-server:
    build:
      context: ./fake-oauth-server
    container_name: fake-oauth-server
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge